In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.preprocessing.image import ImageDataGenerator

# 랜덤시드 고정시키기
np.random.seed(3)


Using TensorFlow backend.


In [2]:
train_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
    './handwriting_shape/train',
    target_size=(24, 24),
    batch_size=3,
    class_mode='categorical')

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
    './handwriting_shape/test',
    target_size=(24, 24),
    batch_size=3,
    class_mode='categorical')

Found 45 images belonging to 3 classes.
Found 15 images belonging to 3 classes.


In [3]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=(24,24,3)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(3, activation='softmax'))


In [4]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [5]:
from IPython.display import display
from PIL import Image
model.fit_generator(
        train_generator,
        steps_per_epoch=15,
        epochs=100,
        validation_data=test_generator,
        validation_steps=5)

Epoch 1/100
15/15 [==============================] - 1s 64ms/step - loss: 0.8232 - accuracy: 0.6444 - val_loss: 0.3354 - val_accuracy: 0.9333
Epoch 2/100
15/15 [==============================] - 0s 23ms/step - loss: 0.1290 - accuracy: 0.9778 - val_loss: 0.0312 - val_accuracy: 0.9333
Epoch 3/100
15/15 [==============================] - 0s 33ms/step - loss: 0.0111 - accuracy: 1.0000 - val_loss: 0.0069 - val_accuracy: 0.9333
Epoch 4/100
15/15 [==============================] - 1s 66ms/step - loss: 0.0173 - accuracy: 1.0000 - val_loss: 3.0317e-04 - val_accuracy: 1.0000
Epoch 5/100
15/15 [==============================] - 1s 48ms/step - loss: 0.0042 - accuracy: 1.0000 - val_loss: 0.0077 - val_accuracy: 1.0000
Epoch 6/100
15/15 [==============================] - 0s 26ms/step - loss: 6.3557e-04 - accuracy: 1.0000 - val_loss: 9.1786e-05 - val_accuracy: 1.0000
Epoch 7/100
15/15 [==============================] - 1s 44ms/step - loss: 2.6595e-04 - accuracy: 1.0000 - val_loss: 6.0528e-04 - val_acc

15/15 [==============================] - 1s 47ms/step - loss: 6.5856e-06 - accuracy: 1.0000 - val_loss: 1.7726e-04 - val_accuracy: 1.0000
Epoch 57/100
15/15 [==============================] - 0s 31ms/step - loss: 6.2915e-06 - accuracy: 1.0000 - val_loss: 0.1192 - val_accuracy: 1.0000
Epoch 58/100
15/15 [==============================] - 0s 33ms/step - loss: 5.9630e-06 - accuracy: 1.0000 - val_loss: 2.8213e-06 - val_accuracy: 1.0000
Epoch 59/100
15/15 [==============================] - 1s 41ms/step - loss: 5.6637e-06 - accuracy: 1.0000 - val_loss: 1.7138e-04 - val_accuracy: 1.0000
Epoch 60/100
15/15 [==============================] - 0s 32ms/step - loss: 5.4226e-06 - accuracy: 1.0000 - val_loss: 0.0413 - val_accuracy: 1.0000
Epoch 61/100
15/15 [==============================] - 0s 17ms/step - loss: 5.2081e-06 - accuracy: 1.0000 - val_loss: 2.6623e-06 - val_accuracy: 1.0000
Epoch 62/100
15/15 [==============================] - 0s 12ms/step - loss: 4.9776e-06 - accuracy: 1.0000 - val_loss

In [6]:
print("-- Evaluate --")
scores = model.evaluate_generator(test_generator, steps=5)
print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))


-- Evaluate --
accuracy: 100.00%


In [7]:
print("-- Predict --")
output = model.predict_generator(test_generator, steps=5)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(test_generator.class_indices)
print(output)


-- Predict --
{'circle': 0, 'rectangle': 1, 'triangle': 2}
[[0.000 0.004 0.996]
 [0.000 0.000 1.000]
 [0.000 0.000 1.000]
 [0.917 0.000 0.083]
 [1.000 0.000 0.000]
 [0.000 1.000 0.000]
 [0.000 0.000 1.000]
 [0.000 1.000 0.000]
 [0.000 1.000 0.000]
 [0.000 0.000 1.000]
 [0.009 0.701 0.289]
 [1.000 0.000 0.000]
 [1.000 0.000 0.000]
 [1.000 0.000 0.000]
 [0.000 1.000 0.000]]
