In [1]:
from __future__ import absolute_import, division, print_function

import tensorflow as tf

In [2]:
print(tf.add(1, 2))
print(tf.add([1, 2], [3, 4]))
print(tf.square(5))
print(tf.reduce_sum([1, 2, 3]))

print(tf.square(2) + tf.square(3))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(13, shape=(), dtype=int32)


In [3]:
x = tf.matmul([[1]], [[2, 3]])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>


In [4]:
x = tf.random.uniform([3, 3])
print(x)

tf.Tensor(
[[0.36650264 0.36245167 0.80039155]
 [0.7418593  0.9707322  0.4758277 ]
 [0.65773404 0.76744723 0.6959398 ]], shape=(3, 3), dtype=float32)


In [6]:
print(tf.test.is_gpu_available())
print(x.device.endswith('GPU:0'))

False
False
